[build]
  command = "next build"
  publish = ".next"
  base = "/portfolio/client-next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://portfolio-api-nfy3.onrender.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 