[build]
  command = "next build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://your-backend-url.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 